---
- name: Update apt cache
  apt: 
    update_cache: yes 
    cache_valid_time: 3600

- name: Install packages
  ansible.builtin.package:
    name:
      - "{{ item }}"
    state: latest
  with_items:
    - python3-pip
    - nginx
    - net-tools
    - git

- name: create web diretory
  file:
    path: /var/www/{{ domain }}
    state: directory
    mode: '0775'
    owner: root
    group: root

- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: copying ngix demosession file
  ansible.builtin.template:
    src:  demosession.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain }}

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/{{ domain }}
    owner: root
    group: root
    mode: '0644'
  notify: 
    - restart nginx service